"""
Django settings for djangologic project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Carga las variables del archivo .env
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-60ys4jw_^x6^2*wdj12gn1!@4keatrrq%lgdtbrsa^svv98i9_'
SECRET_KEY = os.getenv('SECRET_KEY')

#?============================================Desarrollo================================================
DEBUG = True 
ALLOWED_HOSTS = ['*']

#?============================================Produccion================================================
# DEBUG = False

# ALLOWED_HOSTS = ['trivenstores.com','www.trivenstores.com','localhost','3.131.33.181']

# CSRF_TRUSTED_ORIGINS = [
#     'http://3.131.33.181',
#     'http://trivenstores.com',
#     'http://www.trivenstores.com',
# ]

# CSRF_COOKIE_DOMAIN = '.trivenstores.com'  # El punto inicial permite subdominios
# CSRF_COOKIE_SECURE = False  # Cambia a True solo cuando tengas HTTPS (SSL)
# SESSION_COOKIE_SECURE = False # Cambia a True solo cuando tengas HTTPS (SSL)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken', # ¡IMPORTANTE! Para TokenAuthentication
    'corsheaders',
    'products',
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ¡IMPORTANTE: Debe ir primero!
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangologic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.manager_list',
                'products.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangologic.wsgi.application'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        conn_max_age=600,
        # Si la variable de entorno DATABASE_URL NO EXISTE (local), usa esta URL por defecto.
        # ADVERTENCIA: Debes cambiar los datos de usuario/contraseña por algo seguro 
        # y que coincida con tu entorno local.
        default='postgres://Daniel:250806YHJS@localhost:5432/productos_db', 
        
        # O, si usas variables de entorno locales (como en un .env) para la configuración
        # local, simplemente pasa una URL local válida.
    )
}
    


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5500",
    "http://127.0.0.1:5500", # Incluir 127.0.0.1 por si acaso
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Allows for API token-based authentication (will be used for authenticated requests)
        'rest_framework.authentication.TokenAuthentication', 
        # Keep SessionAuthentication for DRF's browsable API if needed
        'rest_framework.authentication.SessionAuthentication', 
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ve'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# RENDER
# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'