# Generated by Django 5.2.7 on 2025-11-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('SALUD', 'Salud y Belleza'), ('HIGIENE', 'Higiene'), ('COMESTIBLES', 'Comestibles'), ('OTROS', 'Otros')], default='OTROS', max_length=11),
        ),
    ]
