# Generated by Django 5.2.7 on 2025-11-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='category',
        ),
    ]
