# Generated by Django 5.2.7 on 2025-11-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_ordendecompra_itemorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='nota_manager',
            field=models.TextField(blank=True, null=True, verbose_name='Nota del Manager'),
        ),
    ]
