# Generated by Django 5.2.7 on 2025-11-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='descripcion_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='nombre_producto_snapshot',
            field=models.CharField(default='Producto Eliminado', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producto'),
        ),
    ]
