# Generated by Django 5.2.7 on 2025-12-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_itemorden_descripcion_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_galeria/'),
        ),
    ]
